version: '2.0'
services:
  app:
    image: 'technikum:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - 5432
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-mysql
      - SPRING_DATASOURCE_USERNAME=compose-mysql
      - SPRING_DATASOURCE_PASSWORD=compose-mysql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: